field_min: 
  - -18
  - 0.0
  - -15.0
field_max:
  - -18
  - 0.0
  - -15.0
step_min:
  - 70.0
  - 25.0
  - 20.0
  - 15.0
step_max:
  - 90.0
  - 52.0
  - 60.0
  - 35.0
  # - 35.0
  # - 42.0
  # - 55.0
  # - 35.0
ts: 5